import { Question } from './question.model';

export const QUESTIONS: Question[] =[
  new Question(1,"As a student of Japanese language and culture you've found yourself at Ohayocon. Upon arriving, you are promptly harrassed by a group of veteran cosplayers. Crying, you turn to find the door only to discover all the doors have disappeared. Alarmed you...", "Decide you might as well make the most of the experience and keep exploring","Set out to begin your escape", 2, 3),
  new Question(2,"You see a shiny object on the ground.","Pick up the shiny","Walk away", 4, 5),
  new Question(3,"You begin to run in the direction with the least amount of people, the wind wiping the tears from your eyes.  A man approaches you with bootleg Dragonball Z DVD's.","Talk to man","Knock them out of his hands and run", 6, 7),
  new Question(4,"You've found a shiny key! Maybe this key will be useful later. For now you put it in your pocket and feel slightly better about this miserable day.","Keep walking","Start looking for doors to unlock", 8, 9),
  new Question(5,"A man approaches you with bootleg Dragonball Z DVD's.","Talk to man","Knock them out of his hands and run", 6, 7),
  new Question(6,"You spark up a converstation with the man selling Dragonball Z DVDs.  After he tells you his whole life story on how he became a DVD bootlegger, he hands you an envelope. He tell you all of the awswers are within.","Take the envelope","Reject the envelope, shout 'No thanks Creep!', and knock the DVDs out of his hands.", 10, 7),
  new Question(7,"The DVDs crash to the floor revealing thousands of beetles living within each DVD case. You gasp and then...","Grab as many as you can! Beetles are the best.","Pass out.", 12, 13),
  new Question(8,"As you walk, you approach a small clutch of vendors. As you browse, you can feel the eyes of a nearby body pillow following you.  You feel compelled to speak to it, but feel really stupid.","Speak to it anyways.","Buy one and take a nap.", 14, 13),
  new Question(9,"You approach a huge door right behind the main stage. It says 'Keep Out. Violators will be prosecuted!' in red text. It has a small keyhole right by the door knob that looks to be just the size of your key.","Try to use your key to open the door","Walk away and try to find another door.", 15, 5),
  new Question(10,"You take the envelope, reluctantly.  The man tells you that it will make sense when you need it most.  You open the envelope and find a paperclip.","Stash the paperclip in your pocket, begin to find your way out again","Make a little figurine out of it, and leave it with the man.", 18, 11),
  new Question(11,"Insulted, the man throws his box of DVD at you, and you fall and hit your head, passing out.","Next"," ", 13, 13),
  new Question(12,"With all your beetle friends now in the pockets of your jacket, life is feeling good again. You stumble upon a door with a sign that says 'Exit'. You give it a push and sunlight streams upon your countenance.","Leave the building","Go back inside", 19, 16),
  new Question(13,"Whamp, whamp. You wake up dressed in Sailor Moon. You're stuck here forever it would seem.","","", 0, 0),
  new Question(14,"The pillow says 'If you remember anything from this experience remember The Alamo'.","Say 'thanks' to the pillow and continue on your merry way.","Get mad at the pillow and take a nap on it to make it shut up.", 2, 13),
  new Question(15,"The door opens and the smell of glitter hits you in the face. Several cosplayers are touching up their makeup inside - some of whom you recognize from the earlier attack. Afraid you...","Quickly run away","Attempt to strike up a conversation", 5, 17),
  new Question(16,"After returning back inside you feel a bite from one of your beetles. Everything around you goes black and you hit the floor.","Next"," ", 13, 13),
  new Question(17,"You feeble attempt at conversation is not rewarded. The cosplayers knock you out with a glitter bomb.","Next"," ", 13, 13),
  new Question(18,"Never know when a paperclip will be handy. Good call!","Next"," ", 8, 8),
  new Question(19,"You've made it out!",""," ", 0, 0),
  new Question(50,"Hello {{userProfile[0].name}}, as a {{userProfile[0].character}} of Firefly you've found yourself as an attendee of Ohayocon. You quickly realize upon your arrival that Nathan Fillion is nowhere in sight, and no one here has heard of Firefly. Disappointed, you turn to find the door only to discover all the doors have disappeared. Alarmed you...", "Decide you might as well make the most of the experience and keep exploring","Set out to begin your escape", 51, 52),
  new Question(51,"Good choice, you decide to keep exploring despite the lack of Nathan Fillion. You see a shiny object on the ground.","Pick up the shiny","Walk away", 54, 55),
  new Question(52,"You look around wildly for the nearest door. A man approaches you with bootleg Dragonball Z DVD's.","Talk to man","Knock them out of his hands and run", 56, 57),
]
